plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lavaz.nexus'
    compileSdk 34

    defaultConfig {
        applicationId "com.lavaz.nexus"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
